version: 0.0
os: linux
files:
  - source: studentapp-artifact/target/studentapp-2.2-SNAPSHOT.war
    destination: apache-tomcat-9.0.96.tar.gz/webapps/

hooks:
  BeforeInstall:
    - location: /install_tomcat.sh
      timeout: 300
      runas: root

   ApplicationStart:
    - location: /start_application.sh
      timeout: 300
      runas: root

      # appspec.yml file for deploy application on ec2
