version: 0.2

phases:
  install:
    commands:
      - echo "Updating package lists..."
      - sudo apt-get update
      - echo "Installing OpenJDK 11..."
      - sudo apt-get install -y openjdk-11-jdk
      - echo "Installing Maven..."
      - sudo apt install maven -y
      - mvn --version  

  build:
    commands:
      - echo "Building the project using Maven..."
      - mvn clean 
      - mvn package

artifacts:
  files:
    - target/*.war  
   